Repository AY2223S1-CS2103T-W09-4/tp, pull requests merged in 2022-10, with the labels that each got.

#54 Branch add attendance
  src/main/java/seedu/address/logic/commands/AttendanceCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/GradeProgressCommand.java
  src/main/java/seedu/address/logic/commands/HomeworkCommand.java
  src/main/java/seedu/address/logic/commands/LessonPlanCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/AttendanceCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/person/Attendance.java
  src/main/java/seedu/address/model/person/AttendanceList.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedAttendance.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AttendanceCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/model/person/AttendanceTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story, priority.High

#57 Branch add view
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AttendanceCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/model/person/AttendanceList.java
  src/main/java/seedu/address/model/person/NameIsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/commands/AttendanceCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
  src/test/java/seedu/address/model/person/NameIsKeywordsPredicateTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/AttendanceTestTypicalPersons.java
Labels: type.Story, priority.High

#71 Updated UI, Person Cards not completed
  src/main/java/seedu/address/model/person/AttendanceList.java
  src/main/java/seedu/address/model/person/GradeProgressList.java
  src/main/java/seedu/address/model/person/HomeworkList.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/resources/images/address_book_32.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: priority.High

#76 Find persons with sessions matching a Day
  src/main/java/seedu/address/logic/commands/SessionCommand.java
  src/main/java/seedu/address/logic/commands/ShowCommand.java
  src/main/java/seedu/address/logic/parser/ShowCommandParser.java
  src/main/java/seedu/address/model/person/DayIsKeywordPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Session.java
  src/main/java/seedu/address/model/person/SessionList.java
  src/test/java/seedu/address/logic/commands/ShowCommandTest.java
  src/test/java/seedu/address/logic/parser/ShowCommandParserTest.java
  src/test/java/seedu/address/model/person/DayIsKeywordPredicateTest.java
Labels: type.Story

#77 Enable assertions
  build.gradle
Labels: type.Task

#82 Branch session patch
  src/main/java/seedu/address/model/person/Session.java
  src/main/java/seedu/address/model/person/SessionList.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug, type.Story, priority.High, severity.Low

#85 Branch release v1.2.1
  build.gradle
  src/main/java/seedu/address/MainApp.java
Labels: priority.High, type.Task

#95 Branch update developerguide
  docs/DeveloperGuide.md
  docs/diagrams/SessionActivity.puml
  docs/diagrams/SessionClassDiagram.puml
  docs/images/SessionActivity.png
  docs/images/SessionDependency.png
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Attendance.java
  src/test/java/seedu/address/model/person/AttendanceTest.java
Labels: priority.High, type.Docs

#100 Fix DG layout
  docs/DeveloperGuide.md
Labels: type.Bug, priority.High, type.Docs, type.Task

#102 Add SessionCommand test for ignore case inputs
  src/test/java/seedu/address/logic/commands/SessionCommandTest.java
Labels: priority.High

#107 add remove command
  src/main/java/seedu/address/logic/commands/RemoveCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RemoveCommandParser.java
  src/main/java/seedu/address/model/person/AttendanceList.java
  src/main/java/seedu/address/model/person/GradeProgressList.java
  src/main/java/seedu/address/model/person/HomeworkList.java
  src/main/java/seedu/address/model/person/SessionList.java
  src/test/java/seedu/address/logic/commands/RemoveCommandTest.java
  src/test/java/seedu/address/logic/parser/RemoveCommandParserTest.java
  src/test/java/seedu/address/testutil/RemovePersonDescriptorBuilder.java
Labels: priority.High, type.Enhancement

#110 Mark command branch
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/main/java/seedu/address/model/person/Attendance.java
  src/main/java/seedu/address/model/person/AttendanceList.java
  src/main/java/seedu/address/model/person/Homework.java
  src/main/java/seedu/address/model/person/HomeworkList.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedAttendance.java
  src/main/java/seedu/address/storage/JsonAdaptedHomework.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/MarkCommandTest.java
  src/test/java/seedu/address/logic/parser/MarkCommandParserTest.java
  src/test/java/seedu/address/model/person/AttendanceTest.java
  src/test/java/seedu/address/testutil/MarkPersonDescriptorBuilder.java
Labels: type.Story, priority.High

#114 Fix bugs, update UG
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AttendanceCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/GradeProgressCommand.java
  src/main/java/seedu/address/logic/commands/HomeworkCommand.java
  src/main/java/seedu/address/logic/commands/LessonPlanCommand.java
  src/main/java/seedu/address/logic/commands/SessionCommand.java
Labels: type.Bug, type.Docs

#119 Update UG
  docs/UserGuide.md
Labels: type.Docs

#120 Fix errors
  docs/UserGuide.md
Labels: type.Bug

#118 Update to disallow commands when in day mode
  src/main/java/seedu/address/logic/commands/AttendanceCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/GradeProgressCommand.java
  src/main/java/seedu/address/logic/commands/HomeworkCommand.java
  src/main/java/seedu/address/logic/commands/LessonPlanCommand.java
  src/main/java/seedu/address/logic/commands/SessionCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AttendanceCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/GradeProgressCommandTest.java
  src/test/java/seedu/address/logic/commands/HomeworkCommandTest.java
  src/test/java/seedu/address/logic/commands/LessonPlanCommandTest.java
  src/test/java/seedu/address/logic/commands/SessionCommandTest.java
  src/test/java/seedu/address/logic/commands/ShowCommandTest.java
Labels: type.Bug, severity.Low

#108 Branch add next session util
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Session.java
  src/main/java/seedu/address/model/util/NextSessionUtil.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/model/util/NextSessionUtilTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug, type.Story, priority.High

#121 Update UG with mark and unmark feature
  docs/UserGuide.md
Labels: type.Docs

#126 Refactor UG
  docs/UserGuide.md
Labels: type.Docs

#125 Branch defensive session
  src/main/java/seedu/address/model/person/Session.java
  src/test/java/seedu/address/model/person/SessionTest.java
Labels: type.Bug, severity.Low

#130 Update dg
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ShowSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/TimeSlotClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ShowSequenceDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/TimeSlotClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/helpMessage.png
Labels: type.Docs

#173 Update ppp and UG bugs from PED
  docs/UserGuide.md
  docs/images/Ui.png
  docs/team/phyliciachristel.md
Labels: type.Docs

#181 Fix command bugs
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/GradeProgressCommand.java
  src/main/java/seedu/address/logic/commands/HomeworkCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/RemoveCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/logic/parser/GradeProgressCommandParser.java
  src/main/java/seedu/address/logic/parser/HomeworkCommandParser.java
  src/main/java/seedu/address/logic/parser/LessonPlanCommandParser.java
  src/main/java/seedu/address/storage/JsonAdaptedAttendance.java
  src/main/java/seedu/address/storage/JsonAdaptedGradeProgress.java
  src/main/java/seedu/address/storage/JsonAdaptedHomework.java
  src/test/java/seedu/address/logic/parser/HomeworkCommandParserTest.java
Labels: type.Bug
